name: build_and_deploy_static

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build
        run: |
          yarn install
          yarn build
      - name: Deploy site to gh-pages branch
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          site-directory: dist
          commit-message: "chore: deploy to gh-pages"
          repo-token: ${{ secrets.GH_PAT }}
          deploy-branch: gh-pages